const actions = {
    ADD_REQUEST: 'ADD_REQUEST',
    CHANGE_NAME: 'CHANGE_NAME',
    CHANGE_DELAY: 'CHANGE_DELAY',
    DELETE_REQUEST: 'DELETE_REQUEST',
    START_REQUESTS: 'START_REQUESTS',
    STOP_REQUESTS: 'STOP_REQUESTS',
    SET_CURRENT_REQUEST: 'SET_CURRENT_REQUEST',
    SET_REQUESTING: 'SET_REQUESTING',
    SET_REQUESTED: 'SET_REQUESTED',
    SET_REQUESTED_ALL: 'SET_REQUESTED_ALL'
};

export {actions};
